### ISSUE TITLE
Git Ignore Trouble

### ISSUE THREAD

**Issue by Simpathey** [Simpathey/Raidme#5]
I attempted to add library files and temp files to the read me. The changes and PR's however are still riddled with these thousands of files which makes it very difficult to track changes.

**Comment by mlordelo** [comment]
If you committed any files/folders before creating the .gitignore, those files/folders will remain tracked by Git. One option to resolve this issue, if this is your issue, is to remove the files/folder from the repo. After doing that, the gitignore should works file.

Another option is to use the `git rm --cached ` command. [StackOverflow question about gitignore](https://stackoverflow.com/questions/45400361/why-is-gitignore-not-ignoring-my-files)

**Comment by Simpathey** [comment]
Thanks! I will give this a try, that is exactly my problem. It is so bad it makes me not wanna work on the project lol.

**Comment by Linus045** [comment]
The problem was that the .gitignore isn't inside the unity directory so the relative paths don't match.
I fixed that with PR #6.
